<?xml version="1.0" encoding="UTF-8"?>
<testng-results skipped="0" failed="2" ignored="0" total="7" passed="5">
  <reporter-output>
  </reporter-output>
  <suite name="Gurukulav0.1" duration-ms="85694" started-at="2019-08-14T17:49:13Z" finished-at="2019-08-14T17:50:39Z">
    <groups>
    </groups>
    <test name="Gurukulav0.1" duration-ms="85694" started-at="2019-08-14T17:49:13Z" finished-at="2019-08-14T17:50:39Z">
      <class name="com.gurukula.testCases.TC_002_LogoutTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_002_LogoutTest@4667ae56]" name="setup" is-config="true" duration-ms="5300" started-at="2019-08-14T17:50:28Z" finished-at="2019-08-14T17:50:33Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="logouttest()[pri:1, instance:com.gurukula.testCases.TC_002_LogoutTest@4667ae56]" name="logouttest" duration-ms="4563" started-at="2019-08-14T17:50:33Z" finished-at="2019-08-14T17:50:38Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- logouttest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.gurukula.testCases.TC_002_LogoutTest@4667ae56]" name="tearDown" is-config="true" duration-ms="827" started-at="2019-08-14T17:50:38Z" finished-at="2019-08-14T17:50:39Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.gurukula.testCases.TC_002_LogoutTest -->
      <class name="com.gurukula.testCases.TC_005_Viewbranch">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_005_Viewbranch@e25b2fe]" name="setup" is-config="true" duration-ms="8293" started-at="2019-08-14T17:49:13Z" finished-at="2019-08-14T17:49:22Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="viewBranch()[pri:0, instance:com.gurukula.testCases.TC_005_Viewbranch@e25b2fe]" name="viewBranch" duration-ms="1362" started-at="2019-08-14T17:49:22Z" finished-at="2019-08-14T17:49:23Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.gurukula.testCases.TC_005_Viewbranch.viewBranch(TC_005_Viewbranch.java:45)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- viewBranch -->
      </class> <!-- com.gurukula.testCases.TC_005_Viewbranch -->
      <class name="com.gurukula.testCases.TC_003_CreateBranch">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_003_CreateBranch@77cd7a0]" name="setup" is-config="true" duration-ms="8491" started-at="2019-08-14T17:49:47Z" finished-at="2019-08-14T17:49:56Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="CreateBranch()[pri:1, instance:com.gurukula.testCases.TC_003_CreateBranch@77cd7a0]" name="CreateBranch" duration-ms="3718" started-at="2019-08-14T17:49:56Z" finished-at="2019-08-14T17:50:00Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- CreateBranch -->
      </class> <!-- com.gurukula.testCases.TC_003_CreateBranch -->
      <class name="com.gurukula.testCases.TC_001_LoginTest">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_001_LoginTest@1a968a59]" name="setup" is-config="true" duration-ms="6306" started-at="2019-08-14T17:50:17Z" finished-at="2019-08-14T17:50:23Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="loginTest()[pri:1, instance:com.gurukula.testCases.TC_001_LoginTest@1a968a59]" name="loginTest" duration-ms="3715" started-at="2019-08-14T17:50:23Z" finished-at="2019-08-14T17:50:27Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- loginTest -->
        <test-method status="PASS" signature="tearDown()[pri:0, instance:com.gurukula.testCases.TC_001_LoginTest@1a968a59]" name="tearDown" is-config="true" duration-ms="859" started-at="2019-08-14T17:50:27Z" finished-at="2019-08-14T17:50:28Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- tearDown -->
      </class> <!-- com.gurukula.testCases.TC_001_LoginTest -->
      <class name="com.gurukula.testCases.TC_007_DeleteBranch">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_007_DeleteBranch@146ba0ac]" name="setup" is-config="true" duration-ms="10232" started-at="2019-08-14T17:49:35Z" finished-at="2019-08-14T17:49:45Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="DeleteBranch()[pri:0, instance:com.gurukula.testCases.TC_007_DeleteBranch@146ba0ac]" name="DeleteBranch" duration-ms="2526" started-at="2019-08-14T17:49:45Z" finished-at="2019-08-14T17:49:47Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- DeleteBranch -->
      </class> <!-- com.gurukula.testCases.TC_007_DeleteBranch -->
      <class name="com.gurukula.testCases.TC_004_SearchBranch">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_004_SearchBranch@204f30ec]" name="setup" is-config="true" duration-ms="9426" started-at="2019-08-14T17:50:00Z" finished-at="2019-08-14T17:50:09Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="FAIL" signature="SearchBranch()[pri:1, instance:com.gurukula.testCases.TC_004_SearchBranch@204f30ec]" name="SearchBranch" duration-ms="7933" started-at="2019-08-14T17:50:09Z" finished-at="2019-08-14T17:50:17Z">
          <exception class="java.lang.AssertionError">
            <message>
              <![CDATA[expected [true] but found [false]]]>
            </message>
            <full-stacktrace>
              <![CDATA[java.lang.AssertionError: expected [true] but found [false]
at org.testng.Assert.fail(Assert.java:96)
at org.testng.Assert.failNotEquals(Assert.java:776)
at org.testng.Assert.assertTrue(Assert.java:44)
at org.testng.Assert.assertTrue(Assert.java:54)
at com.gurukula.testCases.TC_004_SearchBranch.SearchBranch(TC_004_SearchBranch.java:55)
at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:62)
at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
at java.lang.reflect.Method.invoke(Method.java:498)
at org.testng.internal.MethodInvocationHelper.invokeMethod(MethodInvocationHelper.java:124)
at org.testng.internal.Invoker.invokeMethod(Invoker.java:583)
at org.testng.internal.Invoker.invokeTestMethod(Invoker.java:719)
at org.testng.internal.Invoker.invokeTestMethods(Invoker.java:989)
at org.testng.internal.TestMethodWorker.invokeTestMethods(TestMethodWorker.java:125)
at org.testng.internal.TestMethodWorker.run(TestMethodWorker.java:109)
at org.testng.TestRunner.privateRun(TestRunner.java:648)
at org.testng.TestRunner.run(TestRunner.java:505)
at org.testng.SuiteRunner.runTest(SuiteRunner.java:455)
at org.testng.SuiteRunner.runSequentially(SuiteRunner.java:450)
at org.testng.SuiteRunner.privateRun(SuiteRunner.java:415)
at org.testng.SuiteRunner.run(SuiteRunner.java:364)
at org.testng.SuiteRunnerWorker.runSuite(SuiteRunnerWorker.java:52)
at org.testng.SuiteRunnerWorker.run(SuiteRunnerWorker.java:84)
at org.testng.TestNG.runSuitesSequentially(TestNG.java:1208)
at org.testng.TestNG.runSuitesLocally(TestNG.java:1137)
at org.testng.TestNG.runSuites(TestNG.java:1049)
at org.testng.TestNG.run(TestNG.java:1017)
at org.testng.remote.AbstractRemoteTestNG.run(AbstractRemoteTestNG.java:115)
at org.testng.remote.RemoteTestNG.initAndRun(RemoteTestNG.java:251)
at org.testng.remote.RemoteTestNG.main(RemoteTestNG.java:77)
]]>
            </full-stacktrace>
          </exception> <!-- java.lang.AssertionError -->
          <reporter-output>
          </reporter-output>
        </test-method> <!-- SearchBranch -->
      </class> <!-- com.gurukula.testCases.TC_004_SearchBranch -->
      <class name="com.gurukula.testCases.TC_006_Updatebranch">
        <test-method status="PASS" signature="setup()[pri:0, instance:com.gurukula.testCases.TC_006_Updatebranch@754ba872]" name="setup" is-config="true" duration-ms="8071" started-at="2019-08-14T17:49:23Z" finished-at="2019-08-14T17:49:31Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- setup -->
        <test-method status="PASS" signature="updateBranch()[pri:0, instance:com.gurukula.testCases.TC_006_Updatebranch@754ba872]" name="updateBranch" duration-ms="3479" started-at="2019-08-14T17:49:31Z" finished-at="2019-08-14T17:49:35Z">
          <reporter-output>
          </reporter-output>
        </test-method> <!-- updateBranch -->
      </class> <!-- com.gurukula.testCases.TC_006_Updatebranch -->
    </test> <!-- Gurukulav0.1 -->
  </suite> <!-- Gurukulav0.1 -->
</testng-results>
